# POST http://localhost:3001/api/persons
POST https://divine-dust-3869.fly.dev/api/persons
Content-Type: application/json

{
    "name": "John Doe"
    # contact missing number, should not be accepted.
}

