# POST http://localhost:3001/api/persons
POST https://divine-dust-3869.fly.dev/api/persons
Content-Type: application/json

{
    "name": "John Doe",
    "number": "12345"
}

###
# POST http://localhost:3001/api/persons
POST https://divine-dust-3869.fly.dev/api/persons
Content-Type: application/json

{
    "name": "Sally Smith",
    "number": "12345"
}

###
# POST http://localhost:3001/api/persons
POST https://divine-dust-3869.fly.dev/api/persons
Content-Type: application/json

{
    "name": "Cathy Jenkins"
    # contact missing number, should not be accepted.
}





