POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "John Doe",
    "number": "12345"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Sally Smith",
    "number": "12345"
}


